import { Redirect, useRouter } from 'expo-router';
import { Pressable, ScrollView, StyleSheet, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { AppText } from '@/components/ui';
import { colors } from '@/constants/theme';
import { techniqueCards, getTechniqueDisplayId } from '@/data/catalog';
import { useAccess } from '@/access/access-state';
import { useAppState } from '@/state/app-state';
const previewCard = techniqueCards[0];
export default function Welcome() {
 const router=useRouter(); const {accessState}=useAccess(); const {interests,completeOnboarding}=useAppState();
 if(accessState==='paid') return <Redirect href="/(tabs)"/>;
 const startFree=()=>{completeOnboarding(interests);router.replace('/(tabs)');};
 return <SafeAreaView edges={['top','left','right']} style={s.safe}><ScrollView contentContainerStyle={s.page} showsVerticalScrollIndicator={false}>
 <View style={s.hero}><AppText variant="serif" style={s.brand}>処 世 術 禄</AppText><AppText style={s.reading}>しょせいじゅつろく</AppText><AppText variant="serif" style={s.title}>人生をうまく生きる方法を、{'
'}すべての人へ。</AppText><AppText variant="serif" style={s.copy}>流れて消える人生の知識を、{'
'}何度でも使える知恵に。</AppText><View style={s.rule}/><View style={s.stats}><AppText variant="serif" style={s.stat}>216{'
'}<AppText style={s.label}>の処世術</AppText></AppText><View style={s.divider}/><AppText variant="serif" style={s.stat}>526{'
'}<AppText style={s.label}>の理論</AppText></AppText></View></View>
 <View style={s.offer}><AppText variant="serif" style={s.offerTitle}>完全版ですべて解放</AppText><View style={s.offerBody}><View style={s.price}><AppText variant="serif" style={s.priceType}>買い切り</AppText><AppText variant="serif" style={s.amount}>¥280</AppText><AppText style={s.tax}>税込・追加料金なし</AppText></View><View>{['216の処世術をすべて収録','526の理論をすべて収録','いつでもオフラインで読める'].map(x=><AppText key={x} style={s.benefit}>◇　{x}</AppText>)}</View></View><Pressable onPress={()=>router.push('/upgrade')} style={s.primary}><AppText variant="serif" style={s.primaryText}>◇　完全版を手に入れる　›</AppText></Pressable></View>
 <View style={s.preview}><AppText variant="serif" style={s.previewHeading}>収録されている処世術の一例</AppText><View style={s.card}><AppText style={s.num}>No.{getTechniqueDisplayId(previewCard)}</AppText><AppText variant="serif" style={s.cardTitle}>{previewCard.title}</AppText><View style={s.cardRule}/><AppText style={s.tag}>〔 {previewCard.categoryName} 〕</AppText><View style={s.diamond}/></View></View>
 <Pressable onPress={startFree} style={s.secondary}><View><AppText variant="serif" style={s.secondaryTitle}>まずは無料で試す（21件まで）</AppText><AppText style={s.secondarySub}>無料版でも厳選した処世術を体験できます</AppText></View><AppText style={s.arrow}>›</AppText></Pressable><AppText style={s.foot}>買い切りで安心　◇　すぐに利用可能　◇　プライバシー重視</AppText></ScrollView></SafeAreaView>;
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.paper},page:{paddingBottom:32},hero:{backgroundColor:colors.surfaceDark,alignItems:'center',padding:28,paddingBottom:92},brand:{color:'#fff',fontSize:20,letterSpacing:5},reading:{color:'#d6af58',fontSize:10,letterSpacing:2,marginTop:2},title:{color:'#fff',fontSize:28,lineHeight:42,textAlign:'center',marginTop:43},copy:{color:'#d9a947',fontSize:18,lineHeight:28,textAlign:'center',marginTop:16},rule:{width:180,height:1,backgroundColor:'#9b7634',marginTop:24},stats:{flexDirection:'row',alignItems:'center',marginTop:25,gap:30},stat:{color:'#d9a947',fontSize:38,lineHeight:42,textAlign:'center'},label:{color:'#f7eee1',fontSize:17},divider:{height:57,width:1,backgroundColor:'#af8540'},offer:{marginTop:-64,marginHorizontal:22,padding:20,borderRadius:22,borderWidth:1,borderColor:colors.line,backgroundColor:colors.surface},offerTitle:{fontSize:22,textAlign:'center',color:colors.ink},offerBody:{flexDirection:'row',alignItems:'center',justifyContent:'space-around',marginTop:15},price:{width:110,height:110,borderRadius:55,backgroundColor:colors.surfaceDark,alignItems:'center',justifyContent:'center'},priceType:{color:'#d9a947',fontSize:14},amount:{color:'#e0b655',fontSize:35},tax:{color:'#f1e2c4',fontSize:9},benefit:{fontSize:13,color:colors.ink,marginVertical:5},primary:{marginTop:18,backgroundColor:'#bc8525',borderRadius:13,padding:18,alignItems:'center'},primaryText:{color:'#fff',fontSize:19},preview:{alignItems:'center',marginTop:30},previewHeading:{fontSize:20,color:colors.ink,marginBottom:14},card:{width:240,height:280,borderRadius:25,borderWidth:1,borderColor:'#d3a13b',backgroundColor:colors.surfaceDark,alignItems:'center',justifyContent:'center',padding:20},num:{position:'absolute',top:24,color:'#d5a441'},cardTitle:{color:'#fff',fontSize:24,lineHeight:36,textAlign:'center'},cardRule:{width:150,height:1,backgroundColor:'#9d7530',marginTop:21},tag:{color:'#d9a947',marginTop:16},diamond:{position:'absolute',bottom:25,width:15,height:15,borderWidth:1,borderColor:'#d5a441',transform:[{rotate:'45deg'}]},secondary:{marginHorizontal:22,marginTop:26,padding:17,borderRadius:18,borderWidth:1,borderColor:colors.line,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},secondaryTitle:{fontSize:17,color:colors.ink},secondarySub:{fontSize:12,color:colors.inkSoft,marginTop:5},arrow:{fontSize:33,color:colors.ink},foot:{marginTop:26,textAlign:'center',fontSize:10,color:colors.inkSoft}});