import { StyleSheet } from 'react-native';
import { colors, spacing } from '@/constants/theme';

export const ownerCmsStyles = StyleSheet.create({
  screen: { width: '100%', maxWidth: 1720, alignSelf: 'center', padding: spacing.lg, gap: spacing.md },
  eyebrow: { color: colors.gold, fontSize: 11 },
  title: { fontSize: 30 },
  editorTitle: { fontSize: 23, flex: 1 },
  muted: { color: colors.muted, fontSize: 12, lineHeight: 19 },
  heading: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  search: { minHeight: 48, padding: 12, borderWidth: 1, borderColor: colors.line, borderRadius: 8, color: colors.ink, backgroundColor: colors.surface },
  layout: { flexDirection: 'row', gap: 12, alignItems: 'flex-start', minHeight: 690 },
  stacked: { flexDirection: 'column' },
  tree: { width: 230, maxHeight: 770, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.line, borderRadius: 10 },
  compactTree: { width: '100%', maxHeight: 230 },
  treeBody: { padding: 12, gap: 3 },
  treeRow: { paddingVertical: 10, paddingHorizontal: 8, flexDirection: 'row', gap: 5, borderRadius: 6 },
  treeActive: { backgroundColor: '#F3E9D3' },
  treeText: { fontSize: 13, color: colors.ink },
  list: { width: 370, height: 770, padding: 12, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.line, borderRadius: 10, gap: 8 },
  compactList: { width: '100%', height: 330 },
  listHeader: { flexDirection: 'row', justifyContent: 'space-between' },
  rowScroller: { flex: 1 },
  row: { minHeight: 74, flexDirection: 'row', alignItems: 'center', gap: 7, paddingHorizontal: 7, borderBottomWidth: 1, borderBottomColor: colors.line },
  rowActive: { backgroundColor: '#F3E9D3' },
  handle: { color: colors.gold, fontSize: 20 },
  number: { color: colors.muted, width: 26, fontSize: 11 },
  thumb: { width: 38, height: 38, borderRadius: 5 },
  rowCopy: { flex: 1, minWidth: 0 },
  rowTitle: { fontSize: 14, fontWeight: '700', color: colors.ink },
  badge: { fontSize: 10, color: '#41603E', backgroundColor: '#E7F1E4', padding: 5, borderRadius: 5 },
  badgeDraft: { color: '#805C20', backgroundColor: '#FBF0D8' },
  editor: { flex: 1, height: 770, minWidth: 0, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.line, borderRadius: 10 },
  compactEditor: { width: '100%', height: 900 },
  editorBody: { padding: spacing.lg, gap: spacing.md },
  section: { gap: 12, paddingTop: spacing.md, borderTopWidth: 1, borderColor: colors.line },
  sectionTitle: { fontSize: 18 },
  field: { gap: 7 },
  input: { minHeight: 42, padding: 10, borderWidth: 1, borderColor: colors.line, borderRadius: 7, backgroundColor: colors.paper, color: colors.ink },
  multi: { minHeight: 100, textAlignVertical: 'top' },
  actions: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: 8 },
  choice: { padding: 9, borderRadius: 7, borderWidth: 1, borderColor: colors.line },
  choiceActive: { backgroundColor: '#F3E9D3', borderColor: colors.gold },
  chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 5 },
  chip: { maxWidth: 220, padding: 7, borderRadius: 20, backgroundColor: '#F3E9D3' },
  option: { padding: 8, borderBottomWidth: 1, borderColor: colors.line },
  mediaRow: { flexDirection: 'row', gap: 14, alignItems: 'center', flexWrap: 'wrap' },
  mediaPreview: { width: 150, height: 110, borderRadius: 7, backgroundColor: colors.paper, alignItems: 'center', justifyContent: 'center' },
  drop: { padding: 12, borderWidth: 1, borderStyle: 'dashed', borderColor: colors.gold, borderRadius: 7 },
  unsaved: { color: '#A56722', fontSize: 12 },
  error: { padding: 12, color: '#A63F32', backgroundColor: '#FDE9E4' },
  notice: { padding: 12, color: '#41603E', backgroundColor: '#EAF2DF' },
  confirm: { padding: 12, gap: 10, backgroundColor: '#FBF4E3', borderWidth: 1, borderColor: colors.gold, borderRadius: 8 },
  danger: { gap: 9, paddingTop: spacing.md, borderTopWidth: 1, borderColor: colors.line },
});
