import { StyleSheet } from 'react-native';

const ink = '#202327';
const muted = '#6C737A';
const line = '#D9DEE2';
const panel = '#FFFFFF';
const canvas = '#F6F7F8';
const charcoal = '#25292D';

export const ownerCmsStyles = StyleSheet.create({
  screen: { width: '100%', maxWidth: 1960, alignSelf: 'center', paddingHorizontal: 18, paddingTop: 16, paddingBottom: 28, gap: 14, backgroundColor: canvas },
  pageHeader: { alignItems: 'center', gap: 2, paddingVertical: 2 },
  title: { color: ink, fontSize: 25, lineHeight: 33, fontWeight: '700', letterSpacing: 0.2 },
  muted: { color: muted, fontSize: 12, lineHeight: 18 },
  unsaved: { color: '#995122', fontSize: 12, fontWeight: '700' },
  modeSwitch: { flexDirection: 'row', gap: 12 },
  modeCard: { flex: 1, minHeight: 72, paddingHorizontal: 22, paddingVertical: 12, justifyContent: 'center', gap: 4, backgroundColor: panel, borderWidth: 1, borderColor: line, borderRadius: 8 },
  modeCardActive: { backgroundColor: charcoal, borderColor: charcoal },
  modeCardTitle: { color: ink, fontSize: 19, lineHeight: 25, fontWeight: '700' },
  modeCardTitleActive: { color: '#FFFFFF' },
  modeCardDescription: { color: muted, fontSize: 12, lineHeight: 18 },
  modeCardDescriptionActive: { color: '#D7DBDE' },
  layout: { width: '100%', minHeight: 710, flexDirection: 'row', alignItems: 'stretch', gap: 10 },
  stacked: { flexDirection: 'column' },
  tree: { width: '27%', minWidth: 250, height: 710, flexShrink: 0, backgroundColor: panel, borderWidth: 1, borderColor: line, borderRadius: 8 },
  compactTree: { width: '100%', minWidth: 0, height: 300 },
  treeBody: { padding: 12, gap: 4 },
  paneTitleRow: { minHeight: 42, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8, paddingBottom: 10, borderBottomWidth: 1, borderColor: line, zIndex: 10 },
  paneTitle: { color: ink, fontSize: 17, fontWeight: '700' },
  treeRow: { minHeight: 42, paddingVertical: 5, paddingHorizontal: 8, flexDirection: 'row', alignItems: 'center', gap: 8, borderRadius: 5 },
  treeActive: { backgroundColor: '#ECEFF1', borderLeftWidth: 3, borderLeftColor: charcoal, paddingLeft: 5 },
  treeText: { flex: 1, minWidth: 0, color: ink, fontSize: 13, fontWeight: '500' },
  treeCount: { color: muted, fontSize: 11, minWidth: 25, textAlign: 'right' },
  treeDisclosure: { width: 16, color: '#4B5359', fontSize: 16, textAlign: 'center' },
  handle: { width: 17, color: '#61696F', fontSize: 17, textAlign: 'center' },
  handleDisabled: { color: '#C4C9CD' },
  list: { width: '36%', minWidth: 390, height: 710, padding: 12, backgroundColor: panel, borderWidth: 1, borderColor: line, borderRadius: 8, gap: 8 },
  compactList: { width: '100%', minWidth: 0, height: 430 },
  listTop: { gap: 8, zIndex: 10 },
  listHeading: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
  breadcrumb: { flex: 1, color: ink, fontSize: 14, fontWeight: '700' },
  count: { color: muted, fontSize: 12 },
  listControls: { flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: 7 },
  search: { minHeight: 38, paddingHorizontal: 10, paddingVertical: 7, borderWidth: 1, borderColor: line, borderRadius: 6, color: ink, backgroundColor: panel, fontSize: 13 },
  sortControl: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  rowScroller: { flex: 1 },
  row: { minHeight: 62, flexDirection: 'row', alignItems: 'center', gap: 7, paddingHorizontal: 5, borderBottomWidth: 1, borderBottomColor: '#E7EAEC' },
  rowActive: { backgroundColor: '#F0F2F3' },
  number: { width: 28, color: '#5B636A', fontSize: 12, fontWeight: '700', textAlign: 'center' },
  thumb: { width: 34, height: 34, borderRadius: 4 },
  rowCopy: { flex: 1, minWidth: 0, gap: 2, paddingVertical: 7 },
  rowTitle: { color: ink, fontSize: 13, fontWeight: '700' },
  rowSummary: { color: muted, fontSize: 11, lineHeight: 16 },
  badge: { overflow: 'hidden', color: '#365642', backgroundColor: '#E8F0EA', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 14, fontSize: 10, fontWeight: '600' },
  badgeDraft: { color: '#626A70', backgroundColor: '#ECEEEF' },
  badgeArchived: { color: '#7C6868', backgroundColor: '#F2EBEB' },
  menuButton: { width: 28, height: 34, alignItems: 'center', justifyContent: 'center', borderRadius: 5 },
  menuDots: { color: '#4B5359', fontSize: 20, lineHeight: 23 },
  menu: { alignSelf: 'flex-end', minWidth: 190, marginTop: -2, marginRight: 4, marginBottom: 7, padding: 4, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: line, borderRadius: 6, zIndex: 20, elevation: 4 },
  menuItem: { minHeight: 36, justifyContent: 'center', paddingHorizontal: 10, borderRadius: 4 },
  menuItemDanger: { borderTopWidth: 1, borderTopColor: '#F1DDDD', marginTop: 3 },
  menuText: { color: ink, fontSize: 12 },
  menuTextDanger: { color: '#A33030', fontSize: 12 },
  editor: { flex: 1, minWidth: 430, height: 710, backgroundColor: panel, borderWidth: 1, borderColor: line, borderRadius: 8 },
  compactEditor: { width: '100%', minWidth: 0, height: 820 },
  editorBody: { padding: 16, gap: 14 },
  editorHeader: { gap: 5 },
  editorHeading: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 9 },
  editorTitle: { flex: 1, color: ink, fontSize: 22, lineHeight: 30, fontWeight: '700' },
  editorMeta: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 },
  editorTabs: { flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: line },
  editorTab: { minHeight: 40, paddingHorizontal: 11, justifyContent: 'center', borderBottomWidth: 2, borderBottomColor: 'transparent' },
  editorTabActive: { borderBottomColor: charcoal },
  editorTabText: { color: muted, fontSize: 12 },
  editorTabTextActive: { color: ink, fontWeight: '700' },
  section: { gap: 11, paddingTop: 12, borderTopWidth: 1, borderColor: '#E5E8EA' },
  sectionTitle: { color: ink, fontSize: 15, fontWeight: '700' },
  field: { gap: 6 },
  input: { minHeight: 39, paddingHorizontal: 10, paddingVertical: 8, borderWidth: 1, borderColor: line, borderRadius: 5, backgroundColor: '#FFFFFF', color: ink, fontSize: 13 },
  multi: { minHeight: 94, textAlignVertical: 'top' },
  actions: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: 8 },
  choice: { minHeight: 34, paddingHorizontal: 10, paddingVertical: 7, borderRadius: 5, borderWidth: 1, borderColor: line, backgroundColor: '#FFFFFF' },
  choiceActive: { backgroundColor: '#ECEFF1', borderColor: '#8B9399' },
  chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 5 },
  chip: { maxWidth: 220, paddingHorizontal: 9, paddingVertical: 6, borderRadius: 16, backgroundColor: '#ECEFF1' },
  option: { padding: 8, borderBottomWidth: 1, borderColor: line },
  mediaRow: { flexDirection: 'row', gap: 14, alignItems: 'center', flexWrap: 'wrap' },
  mediaPreview: { width: 130, height: 96, borderRadius: 5, backgroundColor: canvas, alignItems: 'center', justifyContent: 'center' },
  drop: { padding: 12, borderWidth: 1, borderStyle: 'dashed', borderColor: '#B9C0C5', borderRadius: 5 },
  error: { padding: 10, color: '#9E3030', backgroundColor: '#FAEEEE', borderRadius: 5, fontSize: 12 },
  notice: { padding: 10, color: '#31543A', backgroundColor: '#EEF4EF', borderRadius: 5, fontSize: 12 },
  confirm: { padding: 12, gap: 9, backgroundColor: '#F7F8F8', borderWidth: 1, borderColor: line, borderRadius: 6 },
  saveBar: { flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between', gap: 12, paddingTop: 14, marginTop: 4, borderTopWidth: 1, borderColor: line },
  saveActions: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'flex-end', gap: 7 },
  danger: { flex: 1, gap: 7 },
  dangerTitle: { color: '#A33030', fontSize: 12, fontWeight: '700' },
  button: { minHeight: 36, paddingHorizontal: 12, paddingVertical: 8, alignItems: 'center', justifyContent: 'center', backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#BFC5C9', borderRadius: 5 },
  buttonCompact: { minHeight: 30, paddingHorizontal: 8, paddingVertical: 5 },
  buttonPrimary: { backgroundColor: charcoal, borderColor: charcoal },
  buttonDanger: { backgroundColor: '#FFFFFF', borderColor: '#C45050' },
  buttonDisabled: { opacity: 0.45 },
  buttonText: { color: ink, fontSize: 12, fontWeight: '600' },
  buttonTextPrimary: { color: '#FFFFFF' },
  buttonTextDanger: { color: '#A33030' },
});
