-- Run against the migrated database. All content mutations are rolled back.
begin;
do $$ declare before_revision bigint; current_revision bigint; target_id text; begin
  select revision into before_revision from public.content_revision where id;
  update public.techniques set updated_at = now() where id = 'master336-001';
  select revision into current_revision from public.content_revision where id;
  if current_revision <> before_revision then raise exception 'Timestamp-only write advanced revision'; end if;
  update public.techniques set draft_display_order = 9999 where id = 'master336-001';
  select revision into current_revision from public.content_revision where id;
  if current_revision <> before_revision then raise exception 'Draft-only write advanced revision'; end if;
  update public.techniques set explanation = explanation || '（更新番号の検証）' where id = 'master336-001';
  select revision into current_revision from public.content_revision where id;
  if current_revision <> before_revision + 1 then raise exception 'Published body did not advance revision exactly once'; end if;
  before_revision := current_revision;
  update public.techniques set status = 'draft' where id = 'master336-356';
  select revision into current_revision from public.content_revision where id;
  if current_revision <> before_revision + 1 then raise exception 'Unpublishing did not advance revision'; end if;
  before_revision := current_revision;
  select id into target_id from public.theories where status='published' limit 1;
  update public.theories set summary = summary || '（更新番号の検証）' where id=target_id;
  select revision into current_revision from public.content_revision where id;
  if current_revision <> before_revision + 1 then raise exception 'Theory update did not advance revision'; end if;
  before_revision := current_revision;
  select id into target_id from public.personas where status='published' limit 1;
  update public.personas set subtitle = coalesce(subtitle,'') || '（検証）' where id=target_id;
  select revision into current_revision from public.content_revision where id;
  if current_revision <> before_revision + 1 then raise exception 'Persona update did not advance revision'; end if;
  before_revision := current_revision;
  update public.content_categories set title=title || '（検証）' where kind='technique' and id='interpersonal';
  select revision into current_revision from public.content_revision where id;
  if current_revision <> before_revision + 1 then raise exception 'Category update did not advance revision'; end if;
  before_revision := current_revision;
  select id into target_id from public.theory_subcategories limit 1;
  update public.theory_subcategories set title=title || '（検証）' where id=target_id;
  select revision into current_revision from public.content_revision where id;
  if current_revision <> before_revision + 1 then raise exception 'Subcategory update did not advance revision'; end if;
  before_revision := current_revision;
  select content_id into target_id from public.paid_content where content_type='learning' limit 1;
  update public.paid_content set payload=jsonb_set(payload,'{title}',to_jsonb(coalesce(payload->>'title','') || '（検証）')) where content_type='learning' and content_id=target_id;
  select revision into current_revision from public.content_revision where id;
  if current_revision <> before_revision + 1 then raise exception 'Learning update did not advance revision'; end if;
  if has_table_privilege('anon','public.content_revision','UPDATE') or has_table_privilege('authenticated','public.content_revision','UPDATE') then raise exception 'Client can write revision'; end if;
  if has_function_privilege('anon','private.bump_content_revision()','EXECUTE') or has_function_privilege('authenticated','private.bump_content_revision()','EXECUTE') then raise exception 'Client can invoke revision trigger'; end if;
end $$;
set local role anon;
select revision from public.content_revision where id = true;
rollback;
