-- Preserve the complete 216/595 catalogue after rotating the free preview selection.
-- These rows were part of the previous public preview, so they were not present
-- in paid_content. Upserting them keeps paid hydration complete while the new
-- public bundle exposes only the newly selected 45 techniques and 20 theories.

insert into public.paid_content (content_type, content_id, payload, sort_order)
values
  ('technique', 'complete-100', '{"id":"complete-100","title":"情報整理を徹底せよ","subtitle":"整理された情報が判断速度を上げる","explanation":"情報が散らかった職場では、能力の高い人まで判断を誤る。メール、口頭、チャット、記憶の中に目的や期限が分散すると、仕事の難しさより「何が決まっていて、何が未決なのか」を探すことに頭を使うからだ。整理とは、見栄えのよい資料を作ることではない。目的、関係者、期限、論点、次の一手を同じ場所に置き、判断に必要なものを迷わず取り出せる状態をつくることである。\n     \n     よくある失敗は、情報を集めすぎて整理した気になることだ。資料が増えても、優先順位と意味づけがなければ、倉庫が大きくなっただけである。重要なのは「この情報から何を決めるのか」を明確にすることだ。\n     \n     整理された一覧は、他者との認識差も露出させる。「当然共有されている」と思っていた前提ほど、文字にした時に食い違いが見つかる。\n     \n     **整理されていない情報は、知識ではなく判断を遅らせる荷物になる。**\n     \n     仕事が詰まったときは、努力を増やす前に、全体を一枚へ戻せ。見える形にした瞬間、問題の半分は作業ではなく混乱だったと気づくことがある。","theoryTagIds":["kb_342"],"tags":["評価の獲得","仕事ができる人"],"status":"published","displayOrder":100,"categoryKey":"work","categoryName":"仕事術","subcategory":"仕事ができる人","articleTitle":"評価の獲得"}'::jsonb, 10000),
  ('technique', 'complete-101', '{"id":"complete-101","title":"完璧な仕事を遅れて出すより、修正できる仕事を早く出せ","subtitle":"早い共有が修正可能性を残す","explanation":"完成度を上げるほど、出すのが怖くなる。自分の中では細部まで理解しているため、未完成な部分ばかりが目につき、「もう少し整えてから」と提出を延ばしてしまう。しかし仕事の価値は、自分一人で完成させることより、正しい方向へ早く進むことにある。六割の段階で共有すれば、目的の誤解や前提のずれを小さいうちに直せる。締切直前の完璧な資料は、方向が違っていても戻る時間がない。\n     \n     早く出すとは、雑に投げることではない。現時点の完成度、未確認点、判断してほしい点を添えて、修正可能な形で渡すことだ。品質が低いまま責任を相手へ移すのとは違う。\n     \n     **仕事では、完成度よりも修正できる時間の方が先に失われる。**\n     \n     早い共有には、上位者を意思決定へ参加させる効果もある。最後に完成品だけを渡すより、途中で判断を借りた方が、成果は共同のものとして守られやすい。\n     \n     自分だけで正解を作ろうとせず、早い段階で他者の視点を借りよ。評価されるのは、最初から誤らない人ではなく、誤りを小さく発見できる人である。","theoryTagIds":["kb_323","kb_330"],"tags":["評価の獲得","仕事ができる人"],"status":"published","displayOrder":101,"categoryKey":"work","categoryName":"仕事術","subcategory":"仕事ができる人","articleTitle":"評価の獲得"}'::jsonb, 10001),
  ('technique', 'complete-102', '{"id":"complete-102","title":"問題だけでなく、選択肢まで運べ","subtitle":"判断材料を持つ人に裁量が集まる","explanation":"「問題が起きました」と報告するだけなら、判断はすべて上司へ戻る。すると次に返ってくるのは、細かな指示と確認である。一方、「原因は二つ考えられます。今日中に復旧するならA、再発防止まで含めるならBです」と選択肢を添える人には、判断を分担できる相手として裁量が集まる。裁量とは、自由を要求して与えられるものではない。相手の判断負荷を減らした結果として渡される。\n     \n     ただし、結論を急いで選択肢を捏造してはいけない。事実、仮説、提案を分け、不明点は不明と示す必要がある。選択肢を出す目的は、自分を賢く見せることではなく、意思決定を前へ進めることだ。\n     \n     選択肢を持ってくる人は、問題を自分の領域として引き受けている。その姿勢が積み重なると、細かな承認を省いても大丈夫だという評判が作られる。\n     \n     **指示される側と相談される側の差は、問題の後ろに次の一手を置けるかで決まる。**\n     \n     報告するときは、「何が起きたか」だけで終わらず、「何を決めれば動くか」まで運べ。","theoryTagIds":["kb_497","kb_498"],"tags":["評価の獲得","仕事ができる人"],"status":"published","displayOrder":102,"categoryKey":"work","categoryName":"仕事術","subcategory":"仕事ができる人","articleTitle":"評価の獲得"}'::jsonb, 10002),
  ('technique', 'complete-103', '{"id":"complete-103","title":"自分の3つの武器を見つけよ","subtitle":"強みの集中が能力を市場価値へ変える","explanation":"「何でもできます」は、一見すると能力の広さを示す言葉だが、仕事を任せる側には「何を頼めば最も力を発揮する人なのか分からない」と映る。組織では、総合点の高さより、特定の場面で真っ先に名前が浮かぶことの方が強い。文章を整える、複雑な利害を整理する、数字から異変を見つける。三つほどの武器が明確になると、仕事の選び方も、周囲からの期待も変わる。\n     \n     武器が曖昧なままだと、空いている仕事へ配置され続け、経験まで他人の都合で形成される。強みを定めることは、将来どの仕事を断るかを決めることでもある。\n     \n     ただし、武器は「好きなこと」だけで決めてはいけない。自分が比較的うまくでき、他者が価値を感じ、繰り返し需要があるものが武器になる。不得意をすべて克服しようとすると、時間は平均化に消え、強みが尖る前に疲れてしまう。\n     \n     **器用さは仕事を増やすが、固有の強みは仕事を選ぶ力をつくる。**\n     \n     自分が勝ちやすい場面を言葉にし、その領域へ経験を集中させよ。能力を増やす前に、「どの問題なら自分を呼ぶべきか」を周囲が説明できる状態をつくることだ。","theoryTagIds":["kb_345"],"tags":["評価の獲得","仕事ができる人"],"status":"published","displayOrder":103,"categoryKey":"work","categoryName":"仕事術","subcategory":"仕事ができる人","articleTitle":"評価の獲得"}'::jsonb, 10003),
  ('technique', 'complete-104', '{"id":"complete-104","title":"何でもやる人になるな。その人しかできない仕事を持て","subtitle":"希少性が仕事の質と交渉力を変える","explanation":"頼まれたことを何でもこなす人は、最初こそ重宝される。しかし仕事の種類を選ばず引き受け続けると、「誰でもできるが誰かがやらなければならない仕事」が集まりやすい。断らないことが能力の証明になるのではなく、代替しやすい労働力として位置づけられるからだ。一方、特定の問題を解ける人には、その領域の仕事と情報が集まり、条件を交渉する余地が生まれる。\n     \n     専門性は狭い知識だけではない。複数部署をつなぐ、難しい説明を翻訳する、混乱した案件を整えるといった、組織内の不足を埋める能力も含まれる。ただし、知識を独占して周囲を依存させるだけでは、信用を失う。\n     \n     専門性を作るには、何でも受ける習慣を止め、学習と深掘りの時間を守る必要がある。便利屋から抜けるには、短期的に一部の依頼を失う覚悟も要る。\n     \n     **何でもできる人は使われやすいが、この問題なら任せたい人は選ばれやすい。**\n     \n     雑務を拒む前に、自分だけが担える価値を育てよ。交渉力は、断る勇気より、断ってもなお必要とされる理由から生まれる。","theoryTagIds":["kb_513","kb_079","kb_468","kb_469"],"tags":["評価の獲得","仕事ができる人"],"status":"published","displayOrder":104,"categoryKey":"work","categoryName":"仕事術","subcategory":"仕事ができる人","articleTitle":"評価の獲得"}'::jsonb, 10004),
  ('technique', 'complete-161', '{"id":"complete-161","title":"忙しさを、充実と取り違えるな","subtitle":"活動量は幸福の質を保証しない","explanation":"予定が埋まっていると、自分が前へ進んでいるように感じる。通知へ返信し、会議を渡り歩き、休む間もなく動く。しかし忙しさは、何を大切にしているかを考えなくて済む便利な煙幕にもなる。活動量が多くても、他人の緊急事態に反応しているだけなら、自分の人生はほとんど動いていない。疲労が充実感に似ているため、両者を取り違えやすい。\n     \n     反対に、静かな一日が空虚とは限らない。誰かと深く話す、考えを整理する、身体を休める時間は、外からは何もしていないように見えても人生を支える。\n     \n     忙しさを減らすと、隠していた不安や空虚さが現れることもある。そこで再び予定を詰めず、何が欠けていたかを見る時間にする。\n     \n     忙しさを手放した後に残る静けさへ耐えることが、本当に望む時間の使い方を見つける入口になる。\n     \n     **忙しさは時間を埋めるが、意味まで埋めてくれるわけではない。**\n     \n     一日の終わりに、こなした数ではなく「今日、自分が大切にしたものは何か」を問え。答えが長く出ないなら、減らすことが次の行動になる。","theoryTagIds":["kb_556","kb_557"],"tags":["人生の指針","人生を豊かにできる人"],"status":"published","displayOrder":161,"categoryKey":"life","categoryName":"人生術","subcategory":"人生を豊かにできる人","articleTitle":"人生の指針"}'::jsonb, 10005),
  ('technique', 'complete-162', '{"id":"complete-162","title":"山頂だけを見続けると、道端の花を見過ごすと心得よ","subtitle":"達成への集中は現在の幸福を隠す","explanation":"向上心の強い人ほど、人生を「目標を達成するまでの待機時間」にしてしまいがちだ。合格したら、昇進したら、成功したら、ようやく人生が始まる。そんなふうに考えているうちに、今日という一日は、未来のために消費されるだけの準備期間になる。\n     \n     目標は人を前へ進ませる。しかし、真面目に努力できる人ほど、成果に結びつかない時間を無価値だと判断しやすい。友人との何気ない会話、遠回りの帰り道、偶然目に入った景色さえ、「今はそんなことをしている場合ではない」と切り捨ててしまう。やがて山頂に着いても、喜びは長く続かない。次の山が現れ、再び「まだ足りない人生」が始まるからだ。\n     \n     **山頂だけを見ていると、人生はいつまでも「まだ始まっていない時間」になる。**\n     \n     道端の花を味わうには、成果にならない時間を罪悪感なく持つ必要がある。休息や雑談を、目標への裏切りと見なさないことだ。\n     \n     目標に向かう日々を、目標のためだけに使ってはならない。未来を勝ち取ることは大切だが、その代償として現在を失えば、人生に勝ったとは言えない。","theoryTagIds":["kb_551","kb_225"],"tags":["人生の指針","人生を豊かにできる人"],"status":"published","displayOrder":162,"categoryKey":"life","categoryName":"人生術","subcategory":"人生を豊かにできる人","articleTitle":"人生の指針"}'::jsonb, 10006),
  ('technique', 'complete-163', '{"id":"complete-163","title":"小さな変化を重ね、日常を濃くせよ","subtitle":"新規性が時間の体感密度を高める","explanation":"同じ道を歩き、同じ店へ入り、同じ情報だけを見る生活は、安定している一方で記憶の境目を失わせる。刺激の少ない日々は速く過ぎ、振り返ると一か月が一枚の薄い記憶に圧縮される。濃い人生に必要なのは、毎週大旅行をすることではない。帰り道を変える、普段読まない分野に触れる、知らない店へ入る。小さな新規性が、時間に輪郭を与える。\n     \n     新規性は大きさより、自分の注意が向いたかで決まる。高価な旅行でも惰性なら薄く、近所の道でも初めて観察すれば濃い経験になる。\n     \n     変化を探す時は、他人に見せる価値より、自分の注意が本当に動くものを選ぶとよい。\n     \n     ただし、変化を求めて予定を詰め込み続ければ、経験は消費されるだけになる。新しいことと、それを味わい記憶へ定着させる余白は一組である。\n     \n     **人生が短く感じられるのは時間が減ったからだけでなく、日々を区別する印が減ったからだ。**\n     \n     退屈を感じたとき、人生全体を変えようとする必要はない。今日の選択を一つだけずらせ。その小さな差が、同じ日常の中に新しい章を作る。","theoryTagIds":["kb_550","kb_268"],"tags":["人生の指針","人生を豊かにできる人"],"status":"published","displayOrder":163,"categoryKey":"life","categoryName":"人生術","subcategory":"人生を豊かにできる人","articleTitle":"人生の指針"}'::jsonb, 10007),
  ('technique', 'complete-164', '{"id":"complete-164","title":"寄り道から、計画では拾えない人生の断片を拾え","subtitle":"偶然の経験が人生の物語を豊かにする","explanation":"効率よく目的地へ着くことばかり考えると、予定にないものはすべて誤差に見える。しかし、後から人生を語るときに残るのは、計画通り進んだ区間より、迷って入った店、断るつもりだった誘い、偶然出会った人だったりする。計画は望む場所へ運ぶが、寄り道は自分が何に心を動かされる人間なのかを教える。\n     \n     寄り道の価値は、その場で役に立つかではなく、自分の関心の方向を発見できるかにもある。\n     \n     もちろん、すべての脱線を美化する必要はない。責任を放棄し、重要な目的を失う寄り道もある。大切なのは、計画を絶対視せず、回復可能な範囲で偶然に席を空けておくことだ。\n     \n     寄り道をした後に元の道へ戻れる目印を持てば、偶然を楽しみながら責任も守れる。余白と帰還可能性が、良い脱線の条件になる。\n     \n     **人生の物語は、予定表を埋めた出来事より、予定表では説明できない出来事から厚くなる。**\n     \n     最短距離だけを正解にするな。時には興味が動いた方向へ一歩それ、その経験が自分をどこへ連れていくかを見る余白を残せ。","theoryTagIds":["kb_552","kb_290"],"tags":["人生の指針","人生を豊かにできる人"],"status":"published","displayOrder":164,"categoryKey":"life","categoryName":"人生術","subcategory":"人生を豊かにできる人","articleTitle":"人生の指針"}'::jsonb, 10008),
  ('technique', 'complete-165', '{"id":"complete-165","title":"一つの顔に閉じこもるな。人生を多面化せよ","subtitle":"複数の役割が自己と世界を広げる","explanation":"仕事で失敗すると人生全体が崩れ、恋愛が終わると自分の価値まで消えたように感じる。一つの役割へ自分を集めすぎると、その領域の出来事が人格全体を占領するからだ。仕事人であると同時に、友人、学ぶ人、旅をする人、家族の一員、何かを作る人でもある。複数の顔を持つことは器用に演じることではなく、自分を一つの評価軸から守ることだ。\n     \n     多面性は、相手ごとに人格を変えることではない。同じ価値観を、仕事、趣味、友情という異なる場所で表現することだ。\n     \n     異なる役割の間を行き来すると、一つの世界で当然とされた価値観を外から見直せる。\n     \n     ただし、役割を増やしすぎて、どこにも深く関われなければ充実は薄くなる。数を競うのではなく、異なる価値を持つ居場所を少しずつ育てる必要がある。\n     \n     **一つの顔だけで生きると、その顔が傷ついた日に人生全体まで傷つく。**\n     \n     自分を説明する言葉を一つに絞らないことだ。何者かである前に、複数の世界に関われる人間であり続けよ。","theoryTagIds":["kb_258","kb_553"],"tags":["人生の指針","人生を豊かにできる人"],"status":"published","displayOrder":165,"categoryKey":"life","categoryName":"人生術","subcategory":"人生を豊かにできる人","articleTitle":"人生の指針"}'::jsonb, 10009),
  ('technique', 'complete-183', '{"id":"complete-183","title":"感情を事実とみなさず、解釈が生んだ反応として扱え","subtitle":"感じたことと、実際に起きたことを切り分ける","explanation":"不安になった、腹が立った、嫌われた気がする。その感情は本物だが、感情が示す解釈まで事実とは限らない。同じ返事の遅れでも、「忙しい」と考えれば待てるが、「軽視された」と考えれば怒りが生まれる。人は出来事そのものより、それが自分にとって何を意味するかという評価に反応している。\n     \n     感情が強いときは、「観察できる事実」「自分の解釈」「生じた感情」を三つに分けて書くとよい。相手が返信していないことは事実だが、自分を嫌っていることは仮説である。この区別ができれば、感情を否定せずに、判断だけを保留できる。\n     \n     **感情は重要な情報だが、現実へ下された最終判決ではない。**\n     \n     反応を無理に消す必要はない。感情が何を守ろうとしているかを聞きつつ、別の説明や追加情報も探せ。感じたことを尊重しながら、解釈に支配されない余地を持て。","theoryTagIds":[],"tags":["内面の管理","感情に振り回されない人"],"status":"published","displayOrder":183,"categoryKey":"life","categoryName":"人生術","subcategory":"感情に振り回されない人","articleTitle":"内面の管理"}'::jsonb, 10010),
  ('technique', 'complete-184', '{"id":"complete-184","title":"感情が強いときに結論を出すな","subtitle":"高ぶった感情は判断基準を変える","explanation":"怒りの中では、相手の一言が人格全体の証拠に見える。悲しみの中では、今の関係が永遠に救われないように感じる。感情が強いとき、判断基準は知らないうちに変わり、その瞬間の痛みを止める選択が最善に見える。\n     \n     **強い感情は重要な情報だが、最終判決を任せるには視野が狭すぎる。**\n     \n     口論の直後に別れを告げる、屈辱を感じた日に退職届を書く、焦りの中で長文を送る。こうした決断は問題を解くより、今の感情から逃げる働きを持ちやすい。「今日は返事をしない」「結論は明日の昼に出す」と決めるだけで、感情と人生の決定を切り離せる。時間を置いても同じ結論なら、その時に実行すればよい。\n     \n     ただし、暴力や安全への脅威がある場合は、その場を離れることを遅らせてはならない。また、冷静になることを口実に問題を放置し続けるのも違う。延期するのは結論であって、事実の確認や安全確保ではない。\n     \n     感情を否定せず、決定権だけは一晩預けない。大きな結論には、熱が下がった自分にも同じ票を与えることだ。","theoryTagIds":["kb_429","kb_430"],"tags":["内面の管理","感情に振り回されない人"],"status":"published","displayOrder":184,"categoryKey":"life","categoryName":"人生術","subcategory":"感情に振り回されない人","articleTitle":"内面の管理"}'::jsonb, 10011),
  ('technique', 'complete-187', '{"id":"complete-187","title":"嫉妬から、自分の欲望を読み取れ","subtitle":"比較の痛みを、自分の望みを知る材料へ変える","explanation":"他人の成功を見て苦しくなると、自分の性格が悪いように感じる。しかし嫉妬は、相手が持つものの中に、自分も価値を置いているものがあるという信号でもある。問題は、その痛みを相手の失敗を願う方向へ使うか、自分の望みを具体化する方向へ使うかである。\n     \n     「何が羨ましいのか」を分解するとよい。肩書そのものか、自由な時間か、人から認められる感覚か。欲しい要素が分かれば、相手と同じ人生を追わずに、自分の方法で近づける。反対に、相手を過小評価して感情を消そうとすると、欲望は見えないまま残る。\n     \n     **嫉妬は、他人を攻撃する許可証ではなく、自分の未整理な願いを映す鏡である。**\n     \n     比較を続けて消耗するなら、情報源から距離を取れ。そのうえで、羨望を一つの行動へ翻訳せよ。学ぶ、応募する、時間を確保する。感情を恥じるより、使い道を選べ。","theoryTagIds":["kb_266"],"tags":["内面の管理","感情に振り回されない人"],"status":"published","displayOrder":187,"categoryKey":"life","categoryName":"人生術","subcategory":"感情に振り回されない人","articleTitle":"内面の管理"}'::jsonb, 10012),
  ('technique', 'complete-188', '{"id":"complete-188","title":"失敗を、人格の欠陥へ広げるな","subtitle":"「失敗した」と「自分は失敗作だ」を分ける","explanation":"同じ失敗でも、「約束を破った」と考える人は修正へ向かえるが、「自分は信用される価値がない」と考える人は隠れたくなる。恥は、問題を一つの行動ではなく、自己全体の欠陥として捉えたときに強くなる。人格全体が裁かれている感覚になるため、謝罪や再挑戦より回避を選びやすい。\n     \n     失敗したら、評価の単位を小さくせよ。何をしたのか、誰にどんな影響が出たのか、何を直せるのかを書く。「自分はだめだ」という言葉は広すぎて、改善点を隠す。行動へ限定すれば、責任を引き受けながら自己破壊を避けられる。\n     \n     **反省は行動を変えるが、恥は自分の存在を消そうとする。**\n     \n     人前で責められた直後は、すぐ自己弁護するか完全に閉じるかの二択になりやすい。まず場を離れ、事実を整理し、必要な謝罪と修正を行え。失敗の責任を負っても、人格全体まで差し出す必要はない。","theoryTagIds":[],"tags":["内面の管理","感情に振り回されない人"],"status":"published","displayOrder":188,"categoryKey":"life","categoryName":"人生術","subcategory":"感情に振り回されない人","articleTitle":"内面の管理"}'::jsonb, 10013),
  ('technique', 'complete-189', '{"id":"complete-189","title":"孤独を、人の少なさだけで判断するな","subtitle":"接触の量ではなく、関係の応答性を見直す","explanation":"大勢の中にいても孤独なことがあり、一人で過ごしていても満たされることがある。孤独を決めるのは、周囲の人数だけではない。自分の考えや感情が届き、必要なときに応答が返る関係があるかどうかである。浅い接点を増やしても、演じ続けなければならない場では孤独は薄まらない。\n     \n     寂しいときに予定だけを詰める前に、「誰の前なら説明しすぎずに話せるか」「誰といると自分を小さくしなくてよいか」を考えよ。いなければ、いきなり深い関係を探すのではなく、同じ場へ繰り返し参加し、小さな自己開示と応答を積む。\n     \n     **孤独は、人がいない状態というより、自分が誰の世界にも届いていないと感じる状態である。**\n     \n     ただし、一人の相手だけに理解のすべてを求めると依存になる。異なる側面を話せる複数の関係を育て、自分自身でも感情を言葉にせよ。理解される入口は、相手を増やすことと、自分を少し見せることの両方から生まれる。","theoryTagIds":[],"tags":["内面の管理","感情に振り回されない人"],"status":"published","displayOrder":189,"categoryKey":"life","categoryName":"人生術","subcategory":"感情に振り回されない人","articleTitle":"内面の管理"}'::jsonb, 10014),
  ('theory', 'kb_001', '{"tagId":"kb_001","originalNumber":1,"title":"初頭効果","summary":"最初に得た情報が、その後の印象や評価の基準として強く残る傾向。第一印象は後から修正しにくいため、関係の入口ほど重要になる。","keyPoints":[],"pitfalls":[],"strategies":[],"applicationConditions":[],"sourceType":"心理学","discipline":"社会心理学","conceptType":"効果・バイアス","domains":["対人術","関係の構築"],"principles":[],"relatedIds":[],"reliability":"学術文献要付与","status":"seed","notes":null,"categoryId":"psychology","categoryTitle":"心理学"}'::jsonb, 10015),
  ('theory', 'kb_005', '{"tagId":"kb_005","originalNumber":5,"title":"類似性魅力効果","summary":"価値観、経歴、趣味などの共通点が多い相手ほど、親しみや信頼を感じやすい傾向。共通点は関係を始める足場になる。","keyPoints":[],"pitfalls":[],"strategies":[],"applicationConditions":[],"sourceType":"心理学","discipline":"社会心理学","conceptType":"効果・バイアス","domains":["対人術","関係の構築"],"principles":[],"relatedIds":[],"reliability":"学術文献要付与","status":"seed","notes":null,"categoryId":"psychology","categoryTitle":"心理学"}'::jsonb, 10016),
  ('theory', 'kb_007', '{"tagId":"kb_007","originalNumber":7,"title":"好意の返報性","summary":"相手から好意を示されると、自分も好意を返したくなりやすい傾向。好意は待つより、先に示すことで循環が生まれる。","keyPoints":[],"pitfalls":[],"strategies":[],"applicationConditions":[],"sourceType":"心理学","discipline":"社会心理学","conceptType":"概念・フレームワーク","domains":["対人術","関係の構築"],"principles":[],"relatedIds":[],"reliability":"学術文献要付与","status":"seed","notes":null,"categoryId":"psychology","categoryTitle":"心理学"}'::jsonb, 10017),
  ('theory', 'kb_008', '{"tagId":"kb_008","originalNumber":8,"title":"自己開示の返報性","summary":"自分の考えや経験を適度に開示すると、相手も同程度の自己開示を返しやすくなる傾向。親密さは一方的ではなく段階的に深まる。","keyPoints":[],"pitfalls":[],"strategies":[],"applicationConditions":[],"sourceType":"心理学","discipline":"社会心理学","conceptType":"概念・フレームワーク","domains":["対人術","関係の構築"],"principles":[],"relatedIds":[],"reliability":"学術文献要付与","status":"seed","notes":null,"categoryId":"psychology","categoryTitle":"心理学"}'::jsonb, 10018),
  ('theory', 'kb_009', '{"tagId":"kb_009","originalNumber":9,"title":"社会的浸透理論","summary":"人間関係は、会話の範囲と深さが少しずつ広がることで親密になるという理論。急激な踏み込みより、相互的な自己開示が重要になる。","keyPoints":[],"pitfalls":[],"strategies":[],"applicationConditions":[],"sourceType":"心理学","discipline":"社会心理学","conceptType":"理論・モデル","domains":["対人術","関係の構築"],"principles":[],"relatedIds":[],"reliability":"学術文献要付与","status":"seed","notes":null,"categoryId":"psychology","categoryTitle":"心理学"}'::jsonb, 10019),
  ('theory', 'kb_010', '{"tagId":"kb_010","originalNumber":10,"title":"不確実性低減理論","summary":"人は初対面の相手について予測できない状態を不快に感じ、質問や観察を通じて不確実性を減らそうとするという理論。安心感は予測可能性から生まれる。","keyPoints":[],"pitfalls":[],"strategies":[],"applicationConditions":[],"sourceType":"心理学","discipline":"社会心理学","conceptType":"理論・モデル","domains":["対人術","関係の構築"],"principles":[],"relatedIds":[],"reliability":"学術文献要付与","status":"seed","notes":null,"categoryId":"psychology","categoryTitle":"心理学"}'::jsonb, 10020),
  ('theory', 'kb_013', '{"tagId":"kb_013","originalNumber":13,"title":"ラポールの三要素モデル","summary":"相互の注意、肯定的な感情、行動の同調がそろうと、自然な信頼関係が生まれるというモデル。会話の内容だけでなく、リズムや雰囲気も重要になる。","keyPoints":[],"pitfalls":[],"strategies":[],"applicationConditions":[],"sourceType":"心理学","discipline":"社会心理学","conceptType":"理論・モデル","domains":["対人術","関係の構築"],"principles":[],"relatedIds":[],"reliability":"学術文献要付与","status":"seed","notes":null,"categoryId":"psychology","categoryTitle":"心理学"}'::jsonb, 10021),
  ('theory', 'kb_130', '{"tagId":"kb_130","originalNumber":130,"title":"ジョブ・クラフティング","summary":"仕事の内容、関係、意味づけを自ら調整し、自分に合う仕事へつくり変える行動。","keyPoints":[],"pitfalls":[],"strategies":[],"applicationConditions":[],"sourceType":"組織・経営論","discipline":"人的資源管理・キャリア論","conceptType":"概念・フレームワーク","domains":["仕事術","評価の獲得"],"principles":[],"relatedIds":[],"reliability":"学術文献要付与","status":"seed","notes":null,"categoryId":"organization-management","categoryTitle":"組織・経営論"}'::jsonb, 10022),
  ('theory', 'kb_131', '{"tagId":"kb_131","originalNumber":131,"title":"キャリア資本理論","summary":"知識、技能、人脈、評判など、職場を越えて持ち運べる資源の蓄積がキャリアを支えるという考え方。","keyPoints":[],"pitfalls":[],"strategies":[],"applicationConditions":[],"sourceType":"組織・経営論","discipline":"人的資源管理・キャリア論","conceptType":"理論・モデル","domains":["仕事術","評価の獲得"],"principles":[],"relatedIds":[],"reliability":"学術文献要付与","status":"seed","notes":null,"categoryId":"organization-management","categoryTitle":"組織・経営論"}'::jsonb, 10023),
  ('theory', 'kb_132', '{"tagId":"kb_132","originalNumber":132,"title":"ピーターの法則","summary":"階層組織では、人は成果を出せた役職から昇進を重ね、やがて能力を発揮できない役職に達しやすいという法則。","keyPoints":[],"pitfalls":[],"strategies":[],"applicationConditions":[],"sourceType":"組織・経営論","discipline":"人的資源管理・キャリア論","conceptType":"原理・法則","domains":["仕事術","評価の獲得"],"principles":[],"relatedIds":[],"reliability":"学術文献要付与","status":"seed","notes":null,"categoryId":"organization-management","categoryTitle":"組織・経営論"}'::jsonb, 10024),
  ('theory', 'kb_133', '{"tagId":"kb_133","originalNumber":133,"title":"プロスペクト理論","summary":"人は絶対的な結果ではなく基準点からの得失で判断し、利益より損失を強く感じるという意思決定理論。","keyPoints":[],"pitfalls":[],"strategies":[],"applicationConditions":[],"sourceType":"行動科学","discipline":"行動経済学","conceptType":"理論・モデル","domains":["仕事術","交渉・合意術"],"principles":[],"relatedIds":[],"reliability":"学術文献要付与","status":"seed","notes":null,"categoryId":"behavioral-science","categoryTitle":"行動科学"}'::jsonb, 10025),
  ('theory', 'kb_136', '{"tagId":"kb_136","originalNumber":136,"title":"現状維持バイアス","summary":"変化の利益があっても、不確実性や損失を避けるため現在の選択を維持しやすい傾向。","keyPoints":[],"pitfalls":[],"strategies":[],"applicationConditions":[],"sourceType":"行動科学","discipline":"行動経済学","conceptType":"効果・バイアス","domains":["仕事術","交渉・合意術"],"principles":[],"relatedIds":[],"reliability":"学術文献要付与","status":"seed","notes":null,"categoryId":"behavioral-science","categoryTitle":"行動科学"}'::jsonb, 10026),
  ('theory', 'kb_222', '{"tagId":"kb_222","originalNumber":222,"title":"アクセプタンス","summary":"不快な感情や思考を無理に消さず、存在を認めたまま必要な行動を取る姿勢。","keyPoints":[],"pitfalls":[],"strategies":[],"applicationConditions":[],"sourceType":"心理学","discipline":"臨床心理学・認知行動療法","conceptType":"概念・フレームワーク","domains":["人生術","不安の解消"],"principles":[],"relatedIds":[],"reliability":"学術文献要付与","status":"seed","notes":null,"categoryId":"psychology","categoryTitle":"心理学"}'::jsonb, 10027),
  ('theory', 'kb_223', '{"tagId":"kb_223","originalNumber":223,"title":"認知的脱フュージョン","summary":"思考を事実や命令としてではなく、頭に浮かんだ言葉やイメージとして距離を置いて捉える方法。","keyPoints":[],"pitfalls":[],"strategies":[],"applicationConditions":[],"sourceType":"心理学","discipline":"臨床心理学・認知行動療法","conceptType":"概念・フレームワーク","domains":["人生術","不安の解消"],"principles":[],"relatedIds":[],"reliability":"学術文献要付与","status":"seed","notes":null,"categoryId":"psychology","categoryTitle":"心理学"}'::jsonb, 10028),
  ('theory', 'kb_224', '{"tagId":"kb_224","originalNumber":224,"title":"脱中心化","summary":"自分の思考や感情を、自分そのものではなく一時的な心の出来事として観察する視点。","keyPoints":[],"pitfalls":[],"strategies":[],"applicationConditions":[],"sourceType":"心理学","discipline":"臨床心理学・認知行動療法","conceptType":"概念・フレームワーク","domains":["人生術","不安の解消"],"principles":[],"relatedIds":[],"reliability":"学術文献要付与","status":"seed","notes":null,"categoryId":"psychology","categoryTitle":"心理学"}'::jsonb, 10029),
  ('theory', 'kb_225', '{"tagId":"kb_225","originalNumber":225,"title":"マインドフルネス","summary":"現在の体験に、評価や判断を加えすぎず意図的に注意を向ける実践。","keyPoints":[],"pitfalls":[],"strategies":[],"applicationConditions":[],"sourceType":"心理学","discipline":"臨床心理学・認知行動療法","conceptType":"概念・フレームワーク","domains":["人生術","不安の解消"],"principles":[],"relatedIds":[],"reliability":"学術文献要付与","status":"seed","notes":null,"categoryId":"psychology","categoryTitle":"心理学"}'::jsonb, 10030),
  ('theory', 'kb_228', '{"tagId":"kb_228","originalNumber":228,"title":"ストレス評価理論","summary":"出来事そのものより、それを脅威と見るか、対処可能と見るかという評価がストレス反応を左右するという理論。","keyPoints":[],"pitfalls":[],"strategies":[],"applicationConditions":[],"sourceType":"心理学","discipline":"臨床心理学・認知行動療法","conceptType":"理論・モデル","domains":["人生術","不安の解消"],"principles":[],"relatedIds":[],"reliability":"学術文献要付与","status":"seed","notes":null,"categoryId":"psychology","categoryTitle":"心理学"}'::jsonb, 10031)
on conflict (content_type, content_id) do update set
  payload = excluded.payload,
  sort_order = excluded.sort_order,
  updated_at = now();

